-- MySQL Script generated by MySQL Workbench
-- Tue Jan 29 10:04:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema atlasofintelligence
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atlasofintelligence
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atlasofintelligence` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `atlasofintelligence` ;

-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_attribute` (
  `attribute_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `description` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_attribute_value` (
  `attribute_value_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1024) NOT NULL,
  `attribute_id` INT NOT NULL,
  PRIMARY KEY (`attribute_value_id`),
  INDEX `fk_task_attribute_value_task_attribute1_idx` (`attribute_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_attribute_value_task_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `atlasofintelligence`.`task_attribute` (`attribute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task` (
  `task_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_has` (
  `has_attribute_id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `attribute_value_id` INT NOT NULL,
  PRIMARY KEY (`has_attribute_id`),
  INDEX `fk_task_has_task_attribute_value1_idx` (`attribute_value_id` ASC) VISIBLE,
  INDEX `fk_task_has_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_has_task_attribute_value1`
    FOREIGN KEY (`attribute_value_id`)
    REFERENCES `atlasofintelligence`.`task_attribute_value` (`attribute_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_has_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `atlasofintelligence`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`source` (
  `source_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `link` VARCHAR(2048) NULL,
  `description` VARCHAR(4096) NULL,
  PRIMARY KEY (`source_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_is`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_is` (
  `is_id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NOT NULL,
  `task_id_in` INT NOT NULL,
  `source_id` INT NOT NULL,
  `weight` FLOAT NULL,
  PRIMARY KEY (`is_id`),
  INDEX `fk_task_is_source1_idx` (`source_id` ASC) VISIBLE,
  INDEX `fk_task_is_task1_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_task_is_task2_idx` (`task_id_in` ASC) VISIBLE,
  CONSTRAINT `fk_task_is_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `atlasofintelligence`.`source` (`source_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_is_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `atlasofintelligence`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_is_task2`
    FOREIGN KEY (`task_id_in`)
    REFERENCES `atlasofintelligence`.`task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent` (
  `agent_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`agent_id`),
  UNIQUE INDEX `agent_id_UNIQUE` (`agent_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_is`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_is` (
  `is_id` INT NOT NULL AUTO_INCREMENT,
  `agent_id` INT NOT NULL,
  `agent_id_in` INT NOT NULL,
  `source_id` INT NOT NULL,
  `weight` FLOAT NULL,
  PRIMARY KEY (`is_id`),
  INDEX `fk_agent_is_source1_idx` (`source_id` ASC) VISIBLE,
  INDEX `fk_agent_is_agent1_idx` (`agent_id` ASC) VISIBLE,
  INDEX `fk_agent_is_agent2_idx` (`agent_id_in` ASC) VISIBLE,
  CONSTRAINT `fk_agent_is_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `atlasofintelligence`.`source` (`source_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_is_agent1`
    FOREIGN KEY (`agent_id`)
    REFERENCES `atlasofintelligence`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_is_agent2`
    FOREIGN KEY (`agent_id_in`)
    REFERENCES `atlasofintelligence`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_attribute` (
  `attribute_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_attribute_value` (
  `attribute_value_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1024) NOT NULL,
  `attribute_id` INT NOT NULL,
  PRIMARY KEY (`attribute_value_id`),
  INDEX `fk_agent_attribute_value_agent_attribute1_idx` (`attribute_id` ASC) VISIBLE,
  CONSTRAINT `fk_agent_attribute_value_agent_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `atlasofintelligence`.`agent_attribute` (`attribute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_has` (
  `has_attribute_id` INT NOT NULL AUTO_INCREMENT,
  `agent_id` INT NOT NULL,
  `attribute_value_id` INT NOT NULL,
  PRIMARY KEY (`has_attribute_id`),
  INDEX `fk_agent_has_agent_attribute_value1_idx` (`attribute_value_id` ASC) VISIBLE,
  INDEX `fk_agent_has_agent1_idx` (`agent_id` ASC) VISIBLE,
  CONSTRAINT `fk_agent_has_agent_attribute_value1`
    FOREIGN KEY (`attribute_value_id`)
    REFERENCES `atlasofintelligence`.`agent_attribute_value` (`attribute_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_has_agent1`
    FOREIGN KEY (`agent_id`)
    REFERENCES `atlasofintelligence`.`agent` (`agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_hierarchy` (
  `hierarchy_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`hierarchy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`agent_belongs_to_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`agent_belongs_to_hierarchy` (
  `belongs_to_hierarchy_id` INT NOT NULL AUTO_INCREMENT,
  `is_id` INT NOT NULL,
  `hierarchy_id` INT NOT NULL,
  PRIMARY KEY (`belongs_to_hierarchy_id`),
  INDEX `fk_agent_belongs_to_hierarchy_agent_is1_idx` (`is_id` ASC) VISIBLE,
  INDEX `fk_agent_belongs_to_hierarchy_agent_hierarchy1_idx` (`hierarchy_id` ASC) VISIBLE,
  CONSTRAINT `fk_agent_belongs_to_hierarchy_agent_is1`
    FOREIGN KEY (`is_id`)
    REFERENCES `atlasofintelligence`.`agent_is` (`is_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_belongs_to_hierarchy_agent_hierarchy1`
    FOREIGN KEY (`hierarchy_id`)
    REFERENCES `atlasofintelligence`.`agent_hierarchy` (`hierarchy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_hierarchy` (
  `hierarchy_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`hierarchy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`task_belongs_to_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`task_belongs_to_hierarchy` (
  `task_belongs_to_hierarchy_id` INT NOT NULL AUTO_INCREMENT,
  `is_id` INT NOT NULL,
  `hierarchy_id` INT NOT NULL,
  PRIMARY KEY (`task_belongs_to_hierarchy_id`),
  INDEX `fk_task_belongs_to_hierarchy_task_is1_idx` (`is_id` ASC) VISIBLE,
  INDEX `fk_task_belongs_to_hierarchy_agent_hierarchy1_idx` (`hierarchy_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_belongs_to_hierarchy_task_is1`
    FOREIGN KEY (`is_id`)
    REFERENCES `atlasofintelligence`.`task_is` (`is_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_belongs_to_hierarchy_agent_hierarchy1`
    FOREIGN KEY (`hierarchy_id`)
    REFERENCES `atlasofintelligence`.`task_hierarchy` (`hierarchy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`method` (
  `method_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  PRIMARY KEY (`method_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`method_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`method_attribute` (
  `attribute_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`attribute_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`method_attribute_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`method_attribute_value` (
  `attribute_value_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(1024) NOT NULL,
  `attribute_id` INT NOT NULL,
  PRIMARY KEY (`attribute_value_id`),
  INDEX `fk_mehotd_attribute_value_method_attribute1_idx` (`attribute_id` ASC) VISIBLE,
  CONSTRAINT `fk_mehotd_attribute_value_method_attribute1`
    FOREIGN KEY (`attribute_id`)
    REFERENCES `atlasofintelligence`.`method_attribute` (`attribute_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`method_has`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`method_has` (
  `has_attribute_id` INT NOT NULL AUTO_INCREMENT,
  `method_id` INT NOT NULL,
  `attribute_value_id` INT NOT NULL,
  `source_id` INT NOT NULL,
  PRIMARY KEY (`has_attribute_id`),
  INDEX `fk_method_has_mehotd_attribute_value1_idx` (`attribute_value_id` ASC) VISIBLE,
  INDEX `fk_method_has_source1_idx` (`source_id` ASC) VISIBLE,
  INDEX `fk_method_has_method1_idx` (`method_id` ASC) VISIBLE,
  CONSTRAINT `fk_method_has_mehotd_attribute_value1`
    FOREIGN KEY (`attribute_value_id`)
    REFERENCES `atlasofintelligence`.`method_attribute_value` (`attribute_value_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_method_has_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `atlasofintelligence`.`source` (`source_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_method_has_method1`
    FOREIGN KEY (`method_id`)
    REFERENCES `atlasofintelligence`.`method` (`method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atlasofintelligence`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atlasofintelligence`.`results` (
  `results_id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(2048) NOT NULL,
  `metric` VARCHAR(2048) NOT NULL,
  `agent_is_id` INT NOT NULL,
  `task_is_id` INT NOT NULL,
  `method_id` INT NOT NULL,
  PRIMARY KEY (`results_id`),
  INDEX `fk_Results_agent_is1_idx` (`agent_is_id` ASC) VISIBLE,
  INDEX `fk_Results_task_is1_idx` (`task_is_id` ASC) VISIBLE,
  INDEX `fk_Results_method1_idx` (`method_id` ASC) VISIBLE,
  CONSTRAINT `fk_Results_agent_is1`
    FOREIGN KEY (`agent_is_id`)
    REFERENCES `atlasofintelligence`.`agent_is` (`is_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_task_is1`
    FOREIGN KEY (`task_is_id`)
    REFERENCES `atlasofintelligence`.`task_is` (`is_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Results_method1`
    FOREIGN KEY (`method_id`)
    REFERENCES `atlasofintelligence`.`method` (`method_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
